#!/usr/bin/env ruby

ROOT = File.expand_path('../..', __FILE__)

$LOAD_PATH.unshift(File.join(ROOT, 'lib'), __FILE__)

Encoding::default_internal = Encoding::UTF_8
Encoding::default_external = Encoding::UTF_8

require 'mft'

begin
  MFT::Cli.new.run(File.join(ROOT, 'templates.yaml'))
rescue StandardError => e
  if e.message != 'exit' # There's probably a better way to do this...
    puts e.message
    exit(1)
  end
end
