#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.join(File.expand_path('../..', __FILE__), 'lib'), __FILE__)

Encoding::default_internal = Encoding::UTF_8
Encoding::default_external = Encoding::UTF_8

require 'mft'

DIRECTORY = File.join(Dir.home, '.mft')

begin
  MFT::Cli.new.run(DIRECTORY)
rescue StandardError => e
  if e.message != 'exit' # There's probably a better way to do this...
    puts e.message
    exit(1)
  end
end
